### ISSUE TITLE
Error: The getter 'labelSmall' isn't defined for the class 'TextTheme'.

### ISSUE THREAD

**Issue by ars27196** [xrr2016/flutter-tree#9]
Flutter is updated to new versions and now TextTheme does not support lableSmall. Please update your Flutter SDKs and Flutter Plugins after that remove the obsolete code to make it useable with the most number of developers. 

 
`/C:/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_tree-2.0.2/lib/src/tree_node.dart:198:57: Error: The getter 'labelSmall' isn't defined for the class 'TextTheme'.`

`- 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('/C:/flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'labelSmall'.
                            Theme.of(context).textTheme.labelSmall?.fontSize,`
                                                        
`/C:/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_tree-2.0.2/lib/src/tree_node.dart:212:57: Error: The getter 'labelSmall' isn't defined for the class 'TextTheme'.`

` - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('/C:/flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'labelSmall'.
                            Theme.of(context).textTheme.labelSmall?.fontSize,`

My Current Flutter Doctor Summary:
> Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 10.0.19041.1415], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1)
[√] IntelliJ IDEA Community Edition (version 2021.2)
[√] VS Code (version 1.52.1)
[√] Connected device (3 available)

• No issues found!

**Comment by xrr2016** [comment]
> Flutter is updated to new versions and now TextTheme does not support lableSmall. Please update your Flutter SDKs and Flutter Plugins after that remove the obsolete code to make it useable with the most number of developers.
> 
> `/C:/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_tree-2.0.2/lib/src/tree_node.dart:198:57: Error: The getter 'labelSmall' isn't defined for the class 'TextTheme'.`
> 
> `- 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('/C:/flutter/packages/flutter/lib/src/material/text_theme.dart'). Try correcting the name to the name of an existing getter, or defining a getter or field named 'labelSmall'. Theme.of(context).textTheme.labelSmall?.fontSize,`
> 
> `/C:/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_tree-2.0.2/lib/src/tree_node.dart:212:57: Error: The getter 'labelSmall' isn't defined for the class 'TextTheme'.`
> 
> ` - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('/C:/flutter/packages/flutter/lib/src/material/text_theme.dart'). Try correcting the name to the name of an existing getter, or defining a getter or field named 'labelSmall'. Theme.of(context).textTheme.labelSmall?.fontSize,`
> 
> My Current Flutter Doctor Summary:
> 
> > Doctor summary (to see all details, run flutter doctor -v):
> > [√] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 10.0.19041.1415], locale en-US)
> > [√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
> > [√] Chrome - develop for the web
> > [√] Android Studio (version 4.1)
> > [√] IntelliJ IDEA Community Edition (version 2021.2)
> > [√] VS Code (version 1.52.1)
> > [√] Connected device (3 available)
> 
> • No issues found!

Updated, please use v2.0.3 https://pub.dev/packages/flutter_tree/install

**Comment by ars27196** [comment]
Thank you for your quick response.
